CREATE TABLE IF NOT EXISTS SUBSCRIPTION
(
    GROUP_ID  INT          NOT NULL,
    USER_ID   INT          NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (GROUP_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS MESSAGE
(
    ID VARCHAR(255) NOT NULL,
    GROUP_ID  INT          NOT NULL,
    USER_ID   INT          NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    MESSAGE VARCHAR2(1024) NOT NULL,
    CREATED BIGINT NOT NULL,
    PRIMARY KEY (ID)
);

